apiVersion: apps/v1
kind: Deployment
metadata:
  name: airflow-deployment
  labels:
    app: airflow
spec:
  replicas: 1
  selector:
    matchLabels:
      app: airflow
  template:
    metadata:
      labels:
        app: airflow
    spec:
      volumes:
      - name: dags
        hostPath:
          path: /home/ubuntu/dag
      containers:
      - name: airflow
        image: puckel/docker-airflow
        ports:
        - containerPort: 8080
        volumeMounts:
        - name: dags
          mountPath: /usr/local/airflow/dags