apiVersion: v1
kind: Service
metadata:
  name: clickhouse-service
spec:
  type: NodePort
  selector:
    app: clickhouse
  ports:
      # By default and for convenience, the `targetPort` is set to the same value as the `port` field.
    - port: 8123
      targetPort: 8123
      # Optional field
      # By default and for convenience, the Kubernetes control plane will allocate a port from a range (default: 30000-32767)
      nodePort: 32123