apiVersion: v1
kind: Service
metadata:
  name: clickhouse-service-2
spec:
  type: NodePort
  selector:
    app: clickhouse
  ports:      
    - port: 9000
      targetPort: 9000      
      nodePort: 32129
      name: client
    - port: 8123
      targetPort: 8123      
      nodePort: 32123
      name: http
